import Anthropic from '@anthropic-ai/sdk';
import { GMBRawData } from './scraper';

export async function generateReport(raw: GMBRawData): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) throw new Error('ANTHROPIC_API_KEY is not set in your .env file.');
  const client = new Anthropic({ apiKey });

  const auditDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric', month: 'long', day: 'numeric',
  });

  const prompt = `You are a Google Business Profile (GBP / GMB) optimization expert. Below is raw text scraped from a Google Maps business listing page. Your job is to:

1. Extract all available business data from the raw text
2. Score the listing across 4 categories (0–100 each)
3. Generate a professional HTML audit report

---
PROFILE URL: ${raw.url}
PAGE TITLE: ${raw.pageTitle}
AUDIT DATE: ${auditDate}

OVERVIEW TEXT (main panel):
${raw.overviewText || '(empty)'}

REVIEWS TAB TEXT:
${raw.reviewsText ? raw.reviewsText.substring(0, 2000) : '(empty)'}

ABOUT TAB TEXT:
${raw.aboutText ? raw.aboutText.substring(0, 2000) : '(empty)'}

---

SCORING RUBRIC (score each 0–100 based strictly on what you can confirm from the text above):

**Basic Info** — 20pts: business name present | 20pts: address present | 20pts: phone present | 20pts: website present | 20pts: hours listed
**Review Profile** — 50pts: rating quality (4.5+=50, 4.0+=38, 3.5+=25, >0=10, missing=0) | 30pts: review count (100+=30, 50+=22, 20+=15, 5+=8, 0=0) | 20pts: owner responds to reviews
**Engagement** — 50pts: photo count (50+=50, 20+=35, 10+=22, 3+=12, 0=0) | 30pts: recent posts/updates (4+=30, 2+=20, 1+=10, 0=0) | 20pts: Q&A entries (5+=20, 1+=10, 0=0)
**Profile Completeness** — 15pts: description/about text | 10pts: business category | 10pts: attributes/amenities listed | 10pts: address | 10pts: phone | 10pts: website | 10pts: hours | 10pts: photos present | 5pts: plus code (indicates verified)

Overall = average of the 4 scores.

---

Generate a complete HTML document. Requirements:
- Start immediately with <!DOCTYPE html> — no text before it
- All CSS in a <style> block in <head> (no inline styles)
- Font: system-ui, -apple-system, sans-serif
- Max-width 860px centered, white background
- Color palette: blue #1a73e8, green #34a853, amber #f9ab00, red #ea4335, dark #202124
- Score badges: large circle, color-coded (green ≥80, amber 60–79, red <60)

REPORT STRUCTURE:
1. **Header** — business name (large), overall score badge, one-line verdict, audit date + URL
2. **Four score cards** in a 2×2 grid — category name, score badge, 1-sentence summary each
3. **Executive Summary** — 3–4 sentences on overall listing health
4. **Detailed Analysis** — one subsection per category:
   - What was found (list the actual values you extracted)
   - What is missing
   - How it compares to a well-optimised profile
5. **Top 5 Priority Actions** — numbered, highest ROI first, each with a concrete step ("Go to your Business Profile → Edit → …")
6. **Positives** — bullet list of what they're already doing well
7. **Footer** — "Generated by GMB Auditor • ${auditDate}"

Be specific and reference the actual data you found. If a field is missing from the raw text, note it as not found and explain the impact.`;

  const message = await client.messages.create({
    model: 'claude-sonnet-4-6',
    max_tokens: 5000,
    messages: [{ role: 'user', content: prompt }],
  });

  const block = message.content[0];
  if (block.type !== 'text') throw new Error('Unexpected Claude response type');

  const raw2 = block.text;
  const fenced = raw2.match(/```html\s*([\s\S]*?)```/i);
  if (fenced) return fenced[1].trim();
  const doctype = raw2.indexOf('<!DOCTYPE html>');
  if (doctype !== -1) return raw2.slice(doctype).trim();
  return raw2.trim();
}
